#include <iostream>
using namespace std;

int main() {
    // Initialize variables
    int a = 10, b = 20, c = 30;
    
    // Add values of a and b, and store in d
    int d = a + b;
    cout << "Value of d (a + b): " << d << endl;
    
    // Subtract c from d, and store in e
    int e = d - c;
    cout << "Value of e (d - c): " << e << endl;
    
    return 0;
}
